sudo: required
services:
  - docker

before_install:
  - docker build -t adrianancuta/playwdocker -f Dockerfile.dev .

script:
  - docker run adrianancuta/playwdocker npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "playwdocker"
  env: "Playwdocker-env"
  bucket_name: "elasticbeanstalk-us-west-2-877491675080"
  bucket_path: "playwdocker"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"